### ISSUE TITLE
fails on build source package step if local dependencies differ from last version on CRAN

### ISSUE THREAD

**Issue by tomjemmett** [r-devel/recheck#3]
Since our package was last published, the list of packages in DEPENDENCIES has changed to include 3 new packages. The action step "download dependencies" is however not installing these new dependencies, so when we move onto the "build source package" step it fails to install due to missing dependencies.

[Example run](https://github.com/nhs-r-community/NHSRplotthedots/actions/runs/9014348108/job/24766860042) + [logs in a gist](https://gist.github.com/tomjemmett/8837b0100496bfc182d0979b2048f4d0)

Is this expected behaviour?

**Comment by TimTaylor** [comment]
Apologies - deleted a too quickly posted erroneous comment when I should have just ~strikethroughed~. 

Hitting the same thing and it does seem like the normal (non reverse) deps are being pulled in based on the CRAN package version not the checked one.

**Comment by jeroen** [comment]
Can you suggest a fix?

**Comment by jeroen** [comment]
Hope this is fixed in https://github.com/r-devel/recheck/commit/34e3a2671d47b4d7ce015279de789c69cf256fc9. Please confirm :)
