### ISSUE TITLE
Add support for checking a package in a subdirectory

### ISSUE THREAD

**Issue by amoeba** [r-devel/recheck#5]
Hello! I'm interested in running recheck on a package that lives in a subdirectory of a repo and I think there's not currently a way to do this. Would you be interested in seeing a PR adding support for that?

**Comment by amoeba** [comment]
Hey @jeroen, just wanted to check in to see if the change in https://github.com/r-devel/recheck/pull/6 would be of interest and if you might have some time in the future to have a look. Thanks in advance.

**Comment by jeroen** [comment]
OK. I think we also need to update the readme for this parameter?

**Comment by amoeba** [comment]
Yeah that would be good. I'll send a follow-on PR to update the README.

**Comment by amoeba** [comment]
Oh, looks like you've already done that. Thank you!

**Comment by jeroen** [comment]
I just did this. Can you confirm if it now works for you?

Op wo 21 aug. 2024 23:52 schreef Bryce Mecum ***@***.***>:

**Comment by amoeba** [comment]
Sure, I'll test now.

**Comment by amoeba** [comment]
I ran it on my fork and it looks like it didn't set the source directory, see the [raw log](https://productionresultssa4.blob.core.windows.net/actions-results/960b2932-f41c-4129-93ab-d9f5a1dad035/workflow-job-run-8771bbc4-bc73-5eb7-a41d-c39d40b8bdae/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-08-21T22%3A12%3A16Z&sig=XxLYIwiaJeCAP7HqoYgvH724SCX5UlXCtsGidXHepuc%3D&ske=2024-08-22T06%3A46%3A30Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-08-21T18%3A46%3A30Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-08-21T22%3A02%3A11Z&sv=2024-05-04). Looking at it now.

**Comment by jeroen** [comment]
I think this may fix it: https://github.com/r-devel/recheck/commit/6434f1016cbb40ae2618235ff862588b8ca021bb

**Comment by amoeba** [comment]
I think that did it. The [docs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs) make the two approaches sound equivalent at least for this use case. Thanks for fixing and for merging the PR!
